In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
b = np.array([[4],[-1],[6]])
b

array([[ 4],
       [-1],
       [ 6]])

In [5]:
C = np.array([[3,-2],
             [7,1]])
C

array([[ 3, -2],
       [ 7,  1]])

In [7]:
D = np.array([
                [3,-2,0,1],
                [7,1,-1,2],
                [4,-5,1,3]
])
D

array([[ 3, -2,  0,  1],
       [ 7,  1, -1,  2],
       [ 4, -5,  1,  3]])

In [11]:
a = np.zeros([1,3])
a[0]

array([0., 0., 0.])

In [17]:
b = np.ones([4,3])
b[0:4]

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [22]:
A = np.array([2,3,4])
A

array([2, 3, 4])

In [24]:
B = np.array([
            [1.2,3.5,5.1],
            [-0.3,1.1,-4.5]])

B

array([[ 1.2,  3.5,  5.1],
       [-0.3,  1.1, -4.5]])

In [33]:
B.shape

(2, 3)

In [34]:
B.ndim

2

In [35]:
B.dtype

dtype('float64')

In [36]:
B.size

6

In [53]:
a = np.array([1,3,5,7,9,11])
a

array([ 1,  3,  5,  7,  9, 11])

In [54]:
B = np.array([
    [2,4,6],
    [-1,5,-3],
    [0,-2,3]
])

B

array([[ 2,  4,  6],
       [-1,  5, -3],
       [ 0, -2,  3]])

In [59]:
a[2:5]

array([5, 7, 9])

In [60]:
a[::-1]

array([11,  9,  7,  5,  3,  1])

In [56]:
B[0]

array([2, 4, 6])

In [57]:
B[2,0]

0

In [61]:
B[1:3,1:3]

array([[ 5, -3],
       [-2,  3]])

In [69]:
A = np.array([[2,3,4]])
A

array([[2, 3, 4]])

In [64]:
B = np.array([[1.2, 3.5, 5.1],
             [-0.3, 1.1, -4.5]])
B

array([[ 1.2,  3.5,  5.1],
       [-0.3,  1.1, -4.5]])

In [71]:
A.T

array([[2],
       [3],
       [4]])

In [66]:
B.T

array([[ 1.2, -0.3],
       [ 3.5,  1.1],
       [ 5.1, -4.5]])

In [73]:
A.T.shape

(3, 1)

In [74]:
C = np.array([[3,-2],
             [7,1]])

In [81]:
det_C = np.linalg.det(C)
det_C == 0

False

In [83]:
inv_C = np.linalg.inv(C)
inv_C

array([[ 0.05882353,  0.11764706],
       [-0.41176471,  0.17647059]])

In [84]:
C @ inv_C 

array([[ 1.00000000e+00, -5.55111512e-17],
       [-5.55111512e-17,  1.00000000e+00]])

In [86]:
D = np.array([[1,5],
             [-3,4]])
D

array([[ 1,  5],
       [-3,  4]])

In [88]:
det_D = np.linalg.det(D)
det_D

18.999999999999996

In [90]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.21052632, -0.26315789],
       [ 0.15789474,  0.05263158]])

In [91]:
D @ D_inv

array([[1.00000000e+00, 3.46944695e-17],
       [0.00000000e+00, 1.00000000e+00]])